INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル1', '内容1', 'author1@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル2', '内容2', 'user2@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user2@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user2@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user2@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user2@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user2@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user2@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user1@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user2@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user4@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user5@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user6@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user7@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user8@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user9@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user10@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user1@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user2@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user4@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user5@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user6@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user7@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user8@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user9@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user10@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user4@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user4@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user4@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user4@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user4@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user5@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user5@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user5@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user1@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル3', '内容3', 'user2@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル61', '内容6', 'user3@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル62', '内容6', 'user4@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル63', '内容6', 'user5@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル64', '内容6', 'user6@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル65', '内容6', 'user6@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル66', '内容6', 'user6@gmail.com', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('タイトル67', '内容6', 'user6@gmail.com', NOW(), NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('user1@gmail.com', 'syh712@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('user2@gmail.com', 'syh712@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('user3@gmail.com', 'syh712@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('user4@gmail.com', 'syh712@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('user5@gmail.com', 'syh712@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('user6@gmail.com', 'syh712@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('user7@gmail.com', 'syh712@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('user8@gmail.com', 'syh712@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('user9@gmail.com', 'syh712@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('user10@gmail.com', 'syh712@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('user11@gmail.com', 'syh712@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('user12@gmail.com', 'syh712@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('user13@gmail.com', 'syh712@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('user14@gmail.com', 'syh712@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('syh712@gmail.com', 'user1@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('syh712@gmail.com', 'user2@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('syh712@gmail.com', 'user3@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('syh712@gmail.com', 'user4@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('syh712@gmail.com', 'user5@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('syh712@gmail.com', 'user6@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('syh712@gmail.com', 'user7@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('syh712@gmail.com', 'user8@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('syh712@gmail.com', 'user9@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('syh712@gmail.com', 'user10@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('syh712@gmail.com', 'user11@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('syh712@gmail.com', 'user12@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('syh712@gmail.com', 'user13@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('syh712@gmail.com', 'user14@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('syh712@gmail.com', 'user15@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('syh712@gmail.com', 'user16@gmail.com', NOW())
INSERT INTO follow (following_user_id, followed_user_id, created_at) VALUES ('syh712@gmail.com', 'user17@gmail.com', NOW())
